# Generated by Django 5.2.7 on 2025-10-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porsche_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='courses_pdf/'),
        ),
    ]
